apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - env:
            - name: PMA_ARBITRARY
              value: "1"
            - name: PMA_HOST
              value: "mariadb.homelab.svc.cluster.local"  # Full service DNS
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: phpmyadmin-secrets
                  key: PMA_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phpmyadmin-secrets
                  key: PMA_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phpmyadmin-secrets
                  key: PMA_ROOT_PASSWORD
          image: phpmyadmin/phpmyadmin
          name: phpmyadmin
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
      restartPolicy: Always
