apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: homelab
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30083  # Access via <NODE_IP>:30909
  selector:
    app: phpmyadmin