apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: phpmyadmin
  name: phpmyadmin
  namespace: homelab
spec:
  ports:
    - name: "9009"
      port: 9009
      targetPort: 80
  selector:
    io.kompose.service: phpmyadmin
status:
  loadBalancer: {}