apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: phpmyadmin
  name: phpmyadmin
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/hasan-mynetwork: "true"
        io.kompose.service: phpmyadmin
    spec:
      containers:
        - env:
            - name: PMA_ARBITRARY
              value: "1"
            - name: PMA_HOST
              value: drnull-db
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: phpmyadmin-secrets
                  key: PMA_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phpmyadmin-secrets
                  key: PMA_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phpmyadmin-secrets
                  key: PMA_ROOT_PASSWORD
          image: phpmyadmin/phpmyadmin
          name: phpmyadmin
          ports:
            - containerPort: 80
              hostPort: 9009
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /usr/local/etc/php/conf.d/uploads.ini
              name: phpmyadmin-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /srv/docker/phpmyadmin/custom-php.ini
          name: phpmyadmin-hostpath0
status: {}