apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: jellyfin
  name: jellyfin
  namespace: homelab
spec:
  ports:
    - name: "9001"
      port: 9001
      targetPort: 8096
  selector:
    io.kompose.service: jellyfin
status:
  loadBalancer: {}