apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv
  namespace: homelab
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /srv/docker/jellyfin
    type: DirectoryOrCreate