apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: metabase
  name: metabase
  namespace: homelab
spec:
  ports:
    - name: "9014"
      port: 9014
      targetPort: 3000
  selector:
    io.kompose.service: metabase
status:
  loadBalancer: {}