apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: drnull-db
  name: drnull-db
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: drnull-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/hasan-mynetwork: "true"
        io.kompose.service: drnull-db
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_USER
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_DATABASE
          image: mariadb
          name: drnull-db
          ports:
            - containerPort: 3306
              hostPort: 3307
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: drnull-db-hostpath0
            - mountPath: /etc/mysql/conf.d
              name: drnull-db-hostpath1
            - mountPath: /etc/localtime
              name: drnull-db-hostpath2
              readOnly: true
            - mountPath: /etc/timezone
              name: drnull-db-hostpath3
              readOnly: true
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /srv/docker/mariadb
          name: drnull-db-hostpath0
        - hostPath:
            path: /srv/docker/mariadb/conf.d
          name: drnull-db-hostpath1
        - hostPath:
            path: /etc/localtime
          name: drnull-db-hostpath2
        - hostPath:
            path: /etc/timezone
          name: drnull-db-hostpath3
status: {}