apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: drnull-db
  name: drnull-db
  namespace: homelab # Ensure this namespace exists
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: drnull-db
  strategy:
    type: Recreate # Good for single-replica stateful apps using hostPath
  template:
    metadata:
      labels:
        io.kompose.network/hasan-mynetwork: "true"
        io.kompose.service: drnull-db
    spec:
      containers:
        - env:
            # Environment variables pulling from 'db-secrets' Secret
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets # Ensure this Secret exists in 'homelab' namespace
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_USER
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_DATABASE
          image: mariadb:latest # It's good practice to use a specific tag like mariadb:10.6
          name: drnull-db
          ports:
            - containerPort: 3306
              hostPort: 3307 # Be cautious with hostPort in production environments
              protocol: TCP
          resources: {} # Consider adding resource requests/limits for stability
          volumeMounts:
            # Mount MariaDB data directory from the main PVC, using a subPath
            - mountPath: /var/lib/mysql
              name: mariadb-data-config-volume # Refers to the volume defined below
              subPath: mysql # Mounts /srv/data/mariadb-persistent/mysql from PV
            # Mount MariaDB config directory from the SAME PVC, using another subPath
            - mountPath: /etc/mysql/conf.d
              name: mariadb-data-config-volume # Refers to the same volume
              subPath: conf.d # Mounts /srv/data/mariadb-persistent/conf.d from PV
            # Mount host's localtime for timezone synchronization
            - mountPath: /etc/localtime
              name: host-localtime # Unique name for this volume mount
              readOnly: true
            # Mount host's timezone for timezone synchronization
            - mountPath: /etc/timezone
              name: host-timezone # Unique name for this volume mount
              readOnly: true
      restartPolicy: Always
      volumes:
        # Define the volume that uses your PersistentVolumeClaim
        - name: mariadb-data-config-volume # This name matches the volumeMounts above
          persistentVolumeClaim:
            claimName: mariadb-pvc # References your new PVC
        # Define the hostPath volume for localtime (kept separate as it's a system file)
        - name: host-localtime
          hostPath:
            path: /etc/localtime
            type: FileOrCreate
        # Define the hostPath volume for timezone (kept separate as it's a system file)
        - name: host-timezone
          hostPath:
            path: /etc/timezone
            type: FileOrCreate
