apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Should match PV capacity
  storageClassName: ""  # Must match PV
  volumeName: mariadb-pv  # Explicit binding