apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 2Gi  # Should match or exceed PVC request
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Good for databases
  storageClassName: ""  # Correct for static provisioning
  hostPath:
    path: /srv/data/mariadb-persistent  # Single directory for all data
    type: DirectoryOrCreate