apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kali
  name: kali
  namespace: homelab
spec:
  ports:
    - name: "2021"
      port: 2021
      targetPort: 22
  selector:
    io.kompose.service: kali
status:
  loadBalancer: {}