apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-pv
  namespace: homelab
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /srv/docker/jupyter
    type: DirectoryOrCreate