apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: jupyter
  name: jupyter
  namespace: homelab
spec:
  ports:
    - name: "9012"
      port: 9012
      targetPort: 8888
  selector:
    io.kompose.service: jupyter
status:
  loadBalancer: {}