apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-db-backup-pv
  namespace: homelab
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /srv/docker/nextcloud/db-backup
    type: DirectoryOrCreate