apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: nextcloud-db
  name: nextcloud-db
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextcloud-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/hasan-mynetwork: "true"
        io.kompose.service: nextcloud-db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_PASSWORD
              value: nextcloud
            - name: MYSQL_ROOT_PASSWORD
              value: nextcloud
            - name: MYSQL_USER
              value: nextcloud
            - name: TZ
              value: Asia/Riyadh
          image: mariadb
          name: nextcloud-db
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: nextcloud-db-storage
            - mountPath: /var/lib/backup
              name: nextcloud-db-backup-storage
            - mountPath: /etc/localtime
              name: host-localtime
              readOnly: true
            - mountPath: /etc/timezone
              name: host-timezone
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: nextcloud-db-storage
          persistentVolumeClaim:
            claimName: nextcloud-db-pvc
        - name: nextcloud-db-backup-storage
          persistentVolumeClaim:
            claimName: nextcloud-db-backup-pvc
        - name: host-localtime
          hostPath:
            path: /etc/localtime
            type: File
        - name: host-timezone
          hostPath:
            path: /etc/timezone
            type: File