apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-db-backup-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  volumeName: nextcloud-db-backup-pv