apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: nextcloud
  name: nextcloud
  namespace: homelab
spec:
  ports:
    - name: "9004"
      port: 9004
      targetPort: 80
  selector:
    io.kompose.service: nextcloud
status:
  loadBalancer: {}