apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qr-drnull-site-tls
  namespace: homelab
spec:
  secretName: qr-drnull-site-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - qr.drnull.site