apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: pgadmin
  name: pgadmin
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pgadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/hasan-mynetwork: "true"
        io.kompose.service: pgadmin
    spec:
      containers:
        - env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secrets
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secrets
                  key: PGADMIN_DEFAULT_PASSWORD
            - name: TZ
              value: Asia/Riyadh
          image: dpage/pgadmin4:latest
          name: pgadmin
          ports:
            - containerPort: 80
              hostPort: 9013
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/pgadmin
              name: pgadmin-hostpath0
            - mountPath: /etc/localtime
              name: pgadmin-hostpath1
              readOnly: true
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /srv/docker/pgadmin/data
          name: pgadmin-hostpath0
        - hostPath:
            path: /etc/localtime
          name: pgadmin-hostpath1
status: {}