apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: filebrowser
  name: filebrowser
  namespace: homelab
spec:
  ports:
    - name: "9005"
      port: 9005
      targetPort: 80
  selector:
    io.kompose.service: filebrowser
status:
  loadBalancer: {}