apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: filebrowser
  name: filebrowser
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: filebrowser
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/hasan-mynetwork: "true"
        io.kompose.service: filebrowser
    spec:
      containers:
        - env:
            - name: FB_DATABASE
              value: /config/database.db
            - name: TZ
              value: Asia/Riyadh
          image: filebrowser/filebrowser
          name: filebrowser
          ports:
            - containerPort: 80
              hostPort: 9005
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: filebrowser-storage
              subPath: config
            - mountPath: /srv
              name: shared-srv-storage
            - mountPath: /etc/localtime
              name: host-localtime
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: filebrowser-storage
          persistentVolumeClaim:
            claimName: filebrowser-pvc
        - name: shared-srv-storage
          hostPath:
            path: /srv
            type: Directory
        - name: host-localtime
          hostPath:
            path: /etc/localtime
            type: File