apiVersion: v1
kind: PersistentVolume
metadata:
  name: pyload-downloads-pv
  namespace: homelab
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /srv/data/pyload
    type: DirectoryOrCreate