apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: pyload
  name: pyload
  namespace: homelab
spec:
  ports:
    - name: "9002"
      port: 9002
      targetPort: 8000
  selector:
    io.kompose.service: pyload
status:
  loadBalancer: {}