apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pyload-downloads-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  volumeName: pyload-downloads-pv