apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pyload-config-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: pyload-config-pv