apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: portainer
  name: portainer
  namespace: homelab
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "8000"
      port: 8000
      targetPort: 8000
    - name: "9443"
      port: 9443
      targetPort: 9443
  selector:
    io.kompose.service: portainer
status:
  loadBalancer: {}