apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: nginx-proxy
  name: nginx-proxy
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/hasan-mynetwork: "true"
        io.kompose.service: nginx-proxy
    spec:
      containers:
        - env:
            - name: TZ
              value: Asia/Riyadh
          image: docker.io/jc21/nginx-proxy-manager:latest
          name: nginx-proxy
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
            - containerPort: 443
              hostPort: 443
              protocol: TCP
            - containerPort: 81
              hostPort: 81
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: nginx-proxy-hostpath0
            - mountPath: /data
              name: nginx-proxy-hostpath1
            - mountPath: /etc/letsencrypt
              name: nginx-proxy-hostpath2
            - mountPath: /etc/localtime
              name: nginx-proxy-hostpath3
              readOnly: true
            - mountPath: /etc/timezone
              name: nginx-proxy-hostpath4
              readOnly: true
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /srv/docker/nginx-proxy/config
          name: nginx-proxy-hostpath0
        - hostPath:
            path: /srv/docker/nginx-proxy/data
          name: nginx-proxy-hostpath1
        - hostPath:
            path: /srv/docker/nginx-proxy/letsencrypt
          name: nginx-proxy-hostpath2
        - hostPath:
            path: /etc/localtime
          name: nginx-proxy-hostpath3
        - hostPath:
            path: /etc/timezone
          name: nginx-proxy-hostpath4
status: {}