apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: vscode
  name: vscode
  namespace: homelab
spec:
  ports:
    - name: "9011"
      port: 9011
      targetPort: 8080
  selector:
    io.kompose.service: vscode
status:
  loadBalancer: {}