apiVersion: v1
kind: PersistentVolume
metadata:
  name: vscode-workspace-pv
  namespace: homelab
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /srv/docker/vscode/workspace
    type: DirectoryOrCreate