apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vscode-ssh-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: vscode-ssh-pv