apiVersion: v1
kind: PersistentVolume
metadata:
  name: vscode-ssh-pv
  namespace: homelab
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /srv/docker/vscode/ssh
    type: DirectoryOrCreate