apiVersion: v1
kind: Secret
metadata:
  name: vscode-secrets
  namespace: homelab
type: Opaque
data:
  VSCODE_PASSWORD: QFltaGFzYW5tZWFkeQ==           # @Ymhasanmeady
  VSCODE_SUDO_PASSWORD: QFltaGFzYW5tZWFkeQ==      # @Ymhasanmeady