apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: syncthing
  name: syncthing
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: SYNCTHING_RECEIVE_FOLDER
              value: /shared-folder/incoming
            - name: TZ
              value: Asia/Riyadh
          image: linuxserver/syncthing
          name: syncthing
          ports:
            - containerPort: 8384
              protocol: TCP
            - containerPort: 22000
              protocol: TCP
            - containerPort: 21027
              protocol: UDP
            - containerPort: 22067
              protocol: UDP
            - containerPort: 22070
              protocol: TCP
            - containerPort: 22070
              protocol: UDP
          resources:
              requests:
                cpu: "3"
                memory: "3Gi"
              limits:
                cpu: "3"
                memory: "3Gi"   
          volumeMounts:
            - mountPath: /config
              name: syncthing-config-storage
            - mountPath: /data
              name: syncthing-data-storage
            - mountPath: /shared-folder
              name: syncthing-share-storage
            - mountPath: /etc/localtime
              name: host-localtime
              readOnly: true
            - mountPath: /etc/timezone
              name: host-timezone
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: syncthing-config-storage
          persistentVolumeClaim:
            claimName: syncthing-config-pvc
        - name: syncthing-data-storage
          persistentVolumeClaim:
            claimName: syncthing-data-pvc
        - name: syncthing-share-storage
          persistentVolumeClaim:
            claimName: syncthing-share-pvc
        - name: host-localtime
          hostPath:
            path: /etc/localtime
            type: File
        - name: host-timezone
          hostPath:
            path: /etc/timezone
            type: File