apiVersion: v1
kind: Service
metadata:
  labels:
    app: syncthing
  name: syncthing
  namespace: homelab
spec:
  type: NodePort
  ports:
    - name: "9003"
      port: 9003
      targetPort: 8384
      nodePort: 30085
    - name: "22000"
      port: 22000
      targetPort: 22000
    - name: "21027"
      port: 21027
      protocol: UDP
      targetPort: 21027
    - name: "22067"
      port: 22067
      protocol: UDP
      targetPort: 22067
    - name: "22070"
      port: 22070
      targetPort: 22070
    - name: 22070-udp
      port: 22070
      protocol: UDP
      targetPort: 22070
  selector:
    app: syncthing
status:
  loadBalancer: {}