apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-data-pv
  namespace: homelab
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /srv/sync-data
    type: DirectoryOrCreate