apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-data-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: syncthing-data-pv