apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: drnull-image
  name: drnull-image
  namespace: homelab
spec:
  ports:
    - name: "9006"
      port: 9006
      targetPort: 8080
  selector:
    io.kompose.service: drnull-image
status:
  loadBalancer: {}