apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: drnull-db
  name: drnull-db
  namespace: homelab
spec:
  ports:
    - name: "3307"
      port: 3307
      targetPort: 3306
  selector:
    io.kompose.service: drnull-db
status:
  loadBalancer: {}