apiVersion: v1
kind: ConfigMap
metadata:
  name: ddclient-config
  namespace: homelab
data:
  ddclient.conf: |
    daemon=300
    syslog=yes
    pid=/var/run/ddclient.pid
    ssl=yes
    protocol=namecheap
    server=dynamicdns.park-your-domain.com
    login=drnull.site
    password=d4c93759447740b5ba4a5fdd5d39461e
    wildcard=YES
    use=web, web=ifconfig.me
    @,drnull.site