apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-reverse-proxy-config
  namespace: homelab
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    
    http {
      upstream npm_http {
        server 127.0.0.1:80;
      }
      
      upstream npm_admin {
        server 127.0.0.1:81;
      }
      
      server {
        listen 8080;
        server_name _;
        
        location / {
          proxy_pass http://npm_http;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
      
      server {
        listen 8081;
        server_name _;
        
        location / {
          proxy_pass http://npm_admin;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-reverse-proxy
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-reverse-proxy
  template:
    metadata:
      labels:
        app: nginx-reverse-proxy
    spec:
      hostNetwork: true
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 8080
        - containerPort: 8081
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-reverse-proxy-config 