apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: homelab
type: Opaque
data:
  admin-password: QEhhMzYxMTM2MTE=
  admin-user: aGFzYW4= #hasan
  db-password: bmV4dGNsb3Vk #  nextcloud
