apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: wordpress
  name: wordpress
  namespace: homelab
spec:
  ports:
    - name: "9010"
      port: 9010
      targetPort: 80
  selector:
    io.kompose.service: wordpress
status:
  loadBalancer: {}