apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress
  namespace: homelab
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30111
  selector:
    app: wordpress
status:
  loadBalancer: {}