apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc # This PVC's name
  namespace: homelab # Ensure this matches your Deployment's namespace
spec:
  volumeName: wordpress-pv # Explicitly binds to nextcloud-pv-0
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: "" # Explicitly no dynamic provisioning