apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: wordpress
  name: wordpress
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/hasan-mynetwork: "true"
        io.kompose.service: wordpress
    spec:
      containers:
        - env:
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress-secrets
                  key: WORDPRESS_DB_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secrets
                  key: WORDPRESS_DB_PASSWORD
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wordpress-secrets
                  key: WORDPRESS_DB_NAME
          image: wordpress:latest
          name: wordpress
          ports:
            - containerPort: 80
              hostPort: 9010
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress-hostpath0
            - mountPath: /etc/localtime
              name: wordpress-hostpath1
              readOnly: true
            - mountPath: /etc/timezone
              name: wordpress-hostpath2
              readOnly: true
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /srv/share/wordpress
          name: wordpress-hostpath0
        - hostPath:
            path: /etc/localtime
          name: wordpress-hostpath1
        - hostPath:
            path: /etc/timezone
          name: wordpress-hostpath2
status: {}